secretgraph/proxy/urls.py
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView

from secretgraph.server.view_decorators import no_opener

from .views import WebmanifestView

app_name = "secretgraph_proxy"


urlpatterns = [
    path(
        "",
        no_opener(
            TemplateView.as_view(
                template_name="secretgraph_proxy/home.html",
            )
        ),
        name="home",
    ),
    path(
        "pcluster/<slug:id>/",
        no_opener(
            TemplateView.as_view(
                template_name="secretgraph_proxy/cluster.html",
            )
        ),
        name="cluster",
    ),
    path(
        "pcontent/<slug:id>/",
        no_opener(
            TemplateView.as_view(
                template_name="secretgraph_proxy/content.html",
            )
        ),
        name="content",
    ),
    path(
        "client/",
        cache_control(max_age=604800)(
            TemplateView.as_view(
                template_name="secretgraph_proxy/webclient.html"
            )
        ),
        name="client",
    ),
    path(
        "webmanifest.json",
        cache_control(max_age=604800)(WebmanifestView.as_view()),
        name="webmanifest.json",
    ),
]

secretgraph/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.utils import timezone
from django.views.decorators.cache import cache_control
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import last_modified
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog

from .schema import schema
from .server.views import CORSFileUploadGraphQLView

last_modified_date = timezone.now()

urlpatterns = [
    # without no contents can be retrieved
    path("secretgraph/", include("secretgraph.server.urls"), name="secretgraph"),
    path(
        "graphql/",
        csrf_exempt(
            CORSFileUploadGraphQLView.as_view(
                graphql_ide="graphiql",
                multipart_uploads_enabled=True,
                schema=schema,
            )
        ),
        name="graphql-plain",
    ),
    # for general favicon, see also linked favicon in template
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("secretgraph/favicon.svg")),
    ),
]
i18n_urlpatterns = []
if not getattr(settings, "SECRETGRAPH_HEADLESS", False):
    i18n_urlpatterns.append(
        path("", include("secretgraph.proxy.urls"), name="secretgraph_proxy")
    )
    i18n_urlpatterns.append(
        path(
            "jsi18n/",
            last_modified(lambda req, **kw: last_modified_date)(
                cache_control(max_age=604800)(
                    JavaScriptCatalog.as_view(
                        domain="django"
                    )  # without domain domainjs is used which is wrong for most stuff
                )
            ),
            name="javascript-i18n",
        )
    )
    # for localized graphql
    # TODO: remove completely as not compatible to strawberry?
    # path(
    #    "graphql",
    #    csrf_exempt(
    #        CORSFileUploadGraphQLView.as_view(
    #            graphiql=True, subscriptions_enabled=True, schema=schema
    #        )
    #    ),
    #    name="graphql-localized",
    # ),

if (
    getattr(settings, "SECRETGRAPH_ADMINAREA", False)
    and "django.contrib.admin" in settings.INSTALLED_APPS
):
    from django.contrib import admin

    i18n_urlpatterns.insert(0, path("admin/", admin.site.urls))

if "django.contrib.auth" in settings.INSTALLED_APPS:
    i18n_urlpatterns.insert(
        0, path("accounts/", include("secretgraph.user.urls"), name="auth")
    )

urlpatterns += i18n_patterns(*i18n_urlpatterns)

secretgraph/proxy/views.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.http import JsonResponse
from django.urls import reverse
from django.views import View
from manifest_loader.utils import manifest


class WebmanifestView(View):
    def get(self, *args, **kwargs):
        return JsonResponse(
            {
                "$schema": "https://json.schemastore.org/web-manifest-combined.json",  # noqa
                "name": "Secretgraph",
                "short_name": "Secretgraph",
                "background_color": "#fff",
                "theme_color": "blue",
                "description": "Secretgraph web client",
                "start_url": reverse("secretgraph_proxy:client"),
                "display": "standalone",
                "icons": [
                    {
                        "src": staticfiles_storage.url(
                            "secretgraph/favicon-192x192.png"
                        ),
                        "sizes": "192x192",
                        "type": "image/png",
                    },
                    {
                        "src": staticfiles_storage.url(
                            "secretgraph/favicon-512x512.png"
                        ),
                        "sizes": "512x512",
                        "type": "image/png",
                    },
                    {
                        "src": staticfiles_storage.url(
                            "secretgraph/favicon.svg"
                        ),
                        "sizes": "any",
                        "purpose": "any maskable",
                        "type": "image/svg+xml",
                    },
                ],
                "serviceworker": {
                    "src": manifest("serviceworker.js"),
                    "scope": "/",
                    "use_cache": True,
                },
            }
        )

secretgraph/proxy/templates/secretgraph_proxy/cluster.html
{% extends "secretgraph_proxy/proxy_base.html" %}
{% load secretgraph %}

{% block content %}
{% fetch_clusters includeIds=id as clusters %}
<div class="container">
    <div class="">
        <h2 class="">Name: <span>{{clusters.0.name|default:""}}</span></h2>
        <div>Description: <span>{{clusters.0.description}}</span></div>
    </div>
    <h3>Contents:</h3>
    {% fetch_contents clusters=id includeTypes="File,Text" excludeTags="mime=image/,mime=video/,mime=audio/" as contents %}
    <div class="container">
        {% for content in contents %}
        <div class="card">
            <h4 class="header">{{content.tags_proxy.name.0|default:""}}</h4>
            <hr/>
            {% if content.type != "Text" %}
            <div class="container">
                <div>Description: <span>{{content.tags_proxy.description.0|default:""}}</span></div>
            </div>
            {% endif %}
            <div class="container">
                {% read_content_sync content=content %}
            </div>
            <a class="footer" href="{% url "secretgraph_proxy:content" id=content.flexid %}">Open</a>
        </div>
        {% endfor %}
    </div>
    <h3>Gallery:</h3>
    {% fetch_contents clusters=id includeTypes="File" includeTags="mime=image/,mime=video/,mime=audio/" as gallery %}
    <div class="container gallery">
        {% for content in gallery %}
        <div class="card">
            <h4 class="header">{{content.tags_proxy.name.0|default:""}}</h4>
            <hr />
            <div class="gallery-entry">
                {% read_content_sync content=content %}
            </div>
            <a class="footer" href="{% url "secretgraph_proxy:content" id=content.flexid %}">Open</a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

secretgraph/proxy/templates/secretgraph_proxy/content.html
{% extends "secretgraph_proxy/proxy_base.html" %}
{% load secretgraph %}

{% block content %}
{% fetch_contents includeIds=id as contents %}
<div class="container">
    <h2>Name: <span>{{contents.0.tags_proxy.name.0|default:""}}</span></h2>
    {# we need to check permissions #}
    {% fetch_clusters includeIds=contents.0.cluster.flexid as clusters %}
    {% if clusters %}
        <div>
            Cluster: <a href="{% url "secretgraph_proxy:cluster" id=contents.0.cluster.flexid %}">{{contents.0.cluster.name}}</a>
        </div>
    {% endif %}
    {% if contents.0.tags_proxy.description.0%}
    <br/><div class="container">
        <div>Description: <span>{{contents.0.tags_proxy.description.0|default:""}}</span></div>
    </div>
    {% endif %}
    <h4>Content:</h4>
    <div class="start-container">
        <div class="bg-white"><div class="container wrapping-pre">{% read_content_sync contents.0 %}</div></div>
    </div>
</div>
{% endblock %}

secretgraph/proxy/templates/secretgraph_proxy/home.html
{% extends "secretgraph_proxy/proxy_base.html" %}
{% load secretgraph %}

{% block content %}
<div class="container">
{% fetch_contents public=True featured=True order_by="-updated" includeTypes="File,Text" includeTags="mime=text/" as contents %}
{% for content in contents %}
{% if forloop.first %}
<div>
<h1>Whats up</h1>
</div>
{% endif %}
<div class="card">
    <h4 class="header">{{content.tags_proxy.name.0|default:""}}</h4>
    <hr />
    {% if content.type == "File" %}
        <div class="container">
            <div>Description: <span>{{content.tags_proxy.description.0|default:""}}</span></div>
        </div>
    {% endif %}
    <div class="container">
{% read_content_sync content=content %}
    </div><hr />
    <a class="footer" href="{% url "secretgraph_proxy:content" id=content.flexid %}">Open</a>
</div>
{% empty %}
No featured contents found
{% endfor %}
</div>
{% endblock %}

secretgraph/proxy/templates/secretgraph_proxy/index.html
{% extends "secretgraph/base.html" %}
{% load manifest %}
{% block styles %}
{% manifest_match '*.css' '<link rel="stylesheet" href="{match}"/>' %}
{% endblock %}
{% block head_scripts %}
{% manifest_match 'runtime.js' '<script src="{match}"></script>' %}
{% manifest_match 'suneditorstyle.js' '<script src="{match}"></script>' %}
{% manifest_match '*vendors*.js' '<script defer src="{match}"></script>' %}
{% manifest_match 'loader.js' '<script defer src="{match}"></script>' %}
{% endblock %}

{% block layout %}
<div id="content-main" data-graphql-path="{{graphql_path}}"></div>
{% endblock %}

secretgraph/proxy/templates/secretgraph_proxy/proxy_base.html
{% extends "secretgraph/base.html" %}
{% load static %}
{% load secretgraph %}
{% block meta %}
{{block.super}}
<link rel="apple-touch-icon" sizes="192x192" href="{% static 'secretgraph/favicon-192x192.png' %}">
<meta name="theme-color" content="#1976d2" />
{% endblock %}
{% block styles %}
{{block.super}}
<style>
    main {
        background-color: #efefef;
        grid-area: main;
        overflow-y: scroll;
    }
    .logo {
        font-size: 30px;
        font-weight:900;
        padding-top: 0;
    }
    .logo img {
        height: 30px;
        margin-top: 8px;
    }
    header {
        width: 100%;
        grid-area: head;
        position: sticky;
        top: 0;
        background-color: #1976d2;
    }
    header > nav {
        margin-left: 12px;
        margin-right: 12px;
        display: flex;
        align-items: center;
    }

    header > nav *{
        color: #FFF;
        font-size: 30px;
        padding: 4px;
    }

    .sidebar {
        grid-area: nav;
        border-right: solid 2px #000;
        display: flex;
        flex-direction: column;
        padding-left: 2px;
        padding-right: 2px;
    }
    .sidebar > * {
        min-height: 20px;
        border-bottom: solid 1px #000;
        vertical-align: middle;
        text-align: left;
        padding: 4px;
        word-break: break-all;
        white-space: pre-wrap;
    }
    .sidebar > *:hover {
        background-color: #efefef;
        cursor: pointer;
    }

    .frame {
        height: 100vh;
        width: 100vw;
        display: grid;
        grid-template-areas: "head head"
                            "nav main"
                            "footer footer";
        grid-template-rows: min-content 1fr;
    }
    .frame-reduced{
        grid-template-columns: 30px 1fr;
        
    }
    .frame-shifted{
        grid-template-columns: 150px 1fr;
    }
    .bg-white {
        background-color: #FFF;
    }
    .card {
        background-color: #FFF;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        margin: 2px;
        margin-bottom: 4px;
    }
    .card:hover {
        box-shadow: 0 6px 10px 0 rgba(0,0,0,0.2);
    }
    .card .header {
        padding: 4px 4px 0 4px;
        display: block;
    }
    .card .footer {
        padding: 0px 4px 4px 4px;
        display: block;
    }

    .container {
        padding: 2px 16px;
        display: block;
    }
    .start-container {
        padding-left: 16px;
        display: block;
    }

    .wrapping-pre pre {
        white-space: pre-wrap;
    }

    footer {
        border-top: solid 2px #000;
        grid-area: footer;
    }

    .footer-grid {
        display: grid;
        grid-template-rows: repeat(3, 1fr);
        grid-auto-columns: minmax(100px, auto);
        gap: 8px;
        padding: 8px;
    }


    .expander {
        min-height: 80vh;
        height: 100%;
    }
    .gallery {
        display: grid;
        grid-template-columns: auto auto auto auto;
    }
    .gallery-entry {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .gallery-entry * {
        max-width: 400px;
        max-height: 400px;
    }
    @media (max-width: 480px) {
        .gallery {
            grid-template-columns: auto;
        }
    }
    @media (max-width: 600px) {
        .gallery {
            grid-template-columns: auto auto;
        }
    }

</style>
{% endblock %}

{% block layout %}
{% fetch_clusters public=True featured=True as clusters %}
{% fetch_contents states="public" includeTypes="Text,File" clusters="@system" allow_system=True order_by="name" as footer_contents %}
<div class="frame frame-shifted">
    <header>
        <nav>
            <a class="logo" href="{% url 'secretgraph_proxy:home' %}">
                <img src="{% static 'secretgraph_proxy/fa-house-solid.svg' %}" alt="Home"/>
            </a>
            <div style="flex-grow: 1;"></div>
            <a href="{% url 'secretgraph_proxy:client' %}" target="secretgraph-client">Webclient</a>
        </nav>
    </header>
    <nav class="sidebar">
        {% for cluster in clusters %}
            <a href="{% url "secretgraph_proxy:cluster" id=cluster.flexid %}" title="{{cluster.description}}">{{cluster.name|default:cluster.flexid_cached}}</a>
        {% endfor %}
    </nav>
    <main class="main">
        {% block content %}
        {% endblock %}
    </main>
    {% if footer_contents %}
    <footer class="footer-grid">
        {% for content in footer_contents %}
            <a href="{% url "secretgraph_proxy:content" id=content.flexid %}" title="{{content.tags_proxy.description.0|default:""}}">{{content.tags_proxy.name.0|default:""}}</a>
        {% endfor %}
    </footer>
    {% endif %}
</div>
{% endblock %}

secretgraph/proxy/templates/secretgraph_proxy/webclient.html
{% extends "secretgraph_proxy/proxy_base.html" %}
{% load manifest %}
{% load secretgraph %}
{% load static %}
{% block styles %}
{{block.super}}
{% manifest_match '*.css' '<link rel="stylesheet" href="{match}"/>' %}
{% endblock %}
{% block meta %}
{{block.super}}
<link rel="manifest" href="{% url 'secretgraph_proxy:webmanifest.json' %}" />
{% endblock %}
{% block head_scripts %}
<script type="module" src="{% manifest 'chunks/runtime~loader.js' %}"></script>
<script type="module" src="{% manifest 'loader.js' %}"></script>
{% endblock %}

{% block layout %}
<div id="secretgraph-webclient" data-sw-url="{% manifest 'serviceworker.js' %}" data-home-url="{% url 'secretgraph_proxy:home' %}" data-graphql-path="{% secretgraph_path %}"></div>
{% endblock %}